"use client"; import { Trash2 } from "lucide-react";
import { SessionForm } from "@/components/forms/studies/sessionForm";
import { Button } from "@/components/ui/button";
import type { StudySession } from "@/components/pages/studies/types"; interface SessionModalProps { show: boolean; userId: string; editSession?: StudySession; existingSubjects: string[]; onSave: (s: StudySession) => Promise<void>; onClose: () => void;
} /** * Modal dinâmico para gerenciamento de sessões (Inclusão e Edição) */
export function SessionModal({ show, userId, editSession, existingSubjects, onSave, onClose,
}: SessionModalProps) { if (!show) return null; return ( <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4 animate-in fade-in duration-200"> <div className="w-full max-w-4xl bg-neutral-900 border border-neutral-800 rounded-3xl p-6 flex flex-col max-h-[95vh] animate-in zoom-in-95 duration-200"> <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar"> <SessionForm userId={userId} initial={editSession} existingSubjects={existingSubjects} onSave={onSave} onCancel={onClose} /> </div> </div> </div> );
} interface DeleteModalProps { id: number | null; onConfirm: (id: number) => Promise<void>; onCancel: () => void;
} /** * Confirmação de exclusão destrutiva */
export function DeleteModal({ id, onConfirm, onCancel }: DeleteModalProps) { if (id === null) return null; return ( <div className="fixed inset-0 z-60 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 animate-in fade-in duration-300"> <div className="w-full max-w-sm bg-neutral-950 border border-red-500/20 rounded-3xl p-8 text-center overflow-hidden animate-in zoom-in-95 duration-300"> <div className="w-16 h-16 rounded-2xl bg-red-500/10 flex items-center justify-center mx-auto mb-5 border border-red-500/20"> <Trash2 className="w-8 h-8 text-red-500" /> </div> <h3 className="text-sm font-bold text-white mb-1"> Remover sessão? </h3> <p className="text-xs text-neutral-500 mb-6"> Essa ação é irreversível e afetará suas estatísticas. </p> <div className="flex gap-3"> <Button type="button" variant="ghost" onClick={onCancel} className="flex-1 py-5 rounded-2xl text-sm font-semibold text-neutral-500 hover:text-white hover:bg-neutral-900 transition-all border-none" > Cancelar </Button> <Button type="button" onClick={() => void onConfirm(id)} className="flex-2 py-5 rounded-2xl bg-red-600 hover:bg-red-500 text-white text-sm font-semibold active:scale-[0.98] transition-all border-none" > Remover </Button> </div> </div> </div> );
}

