"use client"; import { Trash2, X, Moon } from "lucide-react";
import { SleepEntryForm as EntryForm } from "@/components/forms/sleep/sleepEntryForm";
import type { SleepEntry } from "@/components/pages/sleep/types"; interface SleepEntryModalProps { show: boolean; userId: string; editEntry?: SleepEntry; onSave: (e: SleepEntry) => Promise<void>; onClose: () => void;
} export function SleepEntryModal({ show, userId, editEntry, onSave, onClose,
}: SleepEntryModalProps) { if (!show) return null; return ( <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200"> <button type="button" aria-label="Fechar" className="absolute inset-0 w-full h-full cursor-default" onClick={onClose} /> <div className="relative w-full max-w-sm bg-neutral-950 border border-neutral-800 rounded-3xl animate-in zoom-in-95 duration-200 overflow-hidden"> {/* Cabeçalho */} <div className="flex items-center justify-between p-6 border-b border-neutral-800/50 "> <div className="flex items-center gap-3"> <div className="p-2.5 bg-indigo-500/10 rounded-xl border border-indigo-500/20"> <Moon className="w-5 h-5 text-indigo-400" /> </div> <div> <h2 className="text-lg font-bold text-white"> {editEntry ? "Editar registro" : "Registrar sono"} </h2> <p className="text-xs text-neutral-500 mt-0.5">Qualidade do descanso</p> </div> </div> <button type="button" onClick={onClose} className="p-2 rounded-xl hover:bg-neutral-800 text-neutral-500 hover:text-white transition-all cursor-pointer" > <X className="w-5 h-5" /> </button> </div> <div className="p-6"> <EntryForm userId={userId} initial={editEntry} onSave={onSave} onCancel={onClose} /> </div> </div> </div> );
} interface DeleteSleepModalProps { id: number | null; onConfirm: (id: number) => Promise<void>; onCancel: () => void;
} export function DeleteSleepModal({ id, onConfirm, onCancel,
}: DeleteSleepModalProps) { if (id === null) return null; return ( <div className="fixed inset-0 z-60 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200"> <button type="button" aria-label="Fechar" className="absolute inset-0 w-full h-full cursor-default" onClick={onCancel} /> <div className="relative w-full max-w-sm bg-neutral-950 border border-red-500/20 rounded-3xl p-8 text-center overflow-hidden animate-in zoom-in-95 duration-200"> <div className="w-16 h-16 rounded-2xl bg-red-500/10 flex items-center justify-center mx-auto mb-5 border border-red-500/20"> <Trash2 className="w-8 h-8 text-red-500" /> </div> <h3 className="text-sm font-bold text-white mb-1">Remover registro?</h3> <p className="text-xs text-neutral-500 mb-6"> Essa ação é irreversível e afetará suas estatísticas. </p> <div className="flex gap-3"> <button type="button" onClick={onCancel} className="flex-1 py-3 text-sm font-semibold text-neutral-500 hover:text-white transition-colors cursor-pointer" > Cancelar </button> <button type="button" onClick={() => void onConfirm(id)} className="flex-2 py-3 rounded-2xl bg-red-600 hover:bg-red-500 text-white text-sm font-semibold transition-all active:scale-[0.98] cursor-pointer" > Remover </button> </div> </div> </div> );
}

