"use client"; import { Trash2, X, Calendar } from "lucide-react";
import type { CalendarEvent } from "@/components/pages/calendar/types";
import { EventForm } from "@/components/forms/calendar/eventForm"; interface EventModalProps { show: boolean; userId: string; editEvent?: CalendarEvent; onSave: (ev: CalendarEvent) => Promise<void>; onClose: () => void;
} export function EventModal({ show, userId, editEvent, onSave, onClose,
}: EventModalProps) { if (!show) return null; return ( <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200"> <button type="button" aria-label="Fechar" className="absolute inset-0 w-full h-full cursor-default" onClick={onClose} /> <div className="relative w-full max-w-sm bg-neutral-950 border border-neutral-800 rounded-3xl animate-in zoom-in-95 duration-200 overflow-hidden"> {/* Cabeçalho */} <div className="flex items-center justify-between p-6 border-b border-neutral-800/50 "> <div className="flex items-center gap-3"> <div className="p-2.5 bg-green-500/10 rounded-xl border border-green-500/20"> <Calendar className="w-5 h-5 text-green-400" /> </div> <div> <h2 className="text-lg font-bold text-white"> {editEvent ? "Editar evento" : "Novo evento"} </h2> <p className="text-xs text-neutral-500 mt-0.5">Gestão de horários</p> </div> </div> <button type="button" onClick={onClose} className="p-2 rounded-xl hover:bg-neutral-800 text-neutral-500 hover:text-white transition-all cursor-pointer" > <X className="w-5 h-5" /> </button> </div> <div className="p-6"> <EventForm userId={userId} initial={editEvent} onSave={onSave} onCancel={onClose} /> </div> </div> </div> );
} interface DeleteEventModalProps { id: number | null; onConfirm: (id: number) => Promise<void>; onCancel: () => void;
} export function DeleteEventModal({ id, onConfirm, onCancel,
}: DeleteEventModalProps) { if (id === null) return null; return ( <div className="fixed inset-0 z-60 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200"> <button type="button" aria-label="Fechar" className="absolute inset-0 w-full h-full cursor-default" onClick={onCancel} /> <div className="relative w-full max-w-sm bg-neutral-950 border border-neutral-800 rounded-3xl animate-in zoom-in-95 duration-200 overflow-hidden text-center"> {/* Cabeçalho */} <div className="flex flex-col items-center gap-4 p-8 pb-6 border-b border-neutral-800/50 to-transparent"> <div className="p-4 bg-red-500/10 rounded-2xl border border-red-500/20"> <Trash2 className="w-8 h-8 text-red-400" /> </div> <div> <h3 className="text-lg font-bold text-white">Remover evento?</h3> <p className="text-xs text-neutral-500 mt-1 px-4 leading-relaxed"> Essa ação é irreversível e removerá o item do seu calendário. </p> </div> </div> {/* Ações */} <div className="p-6 flex flex-col gap-3 pt-4"> <button type="button" onClick={() => void onConfirm(id)} className="w-full flex items-center justify-center gap-2.5 py-3.5 rounded-xl bg-red-500/10 hover:bg-red-500/20 border border-red-500/60 hover:border-red-400 text-red-300 hover:text-red-200 font-semibold text-sm transition-all active:scale-[0.98] cursor-pointer" > <Trash2 className="w-4 h-4" /> Remover </button> <button type="button" onClick={onCancel} className="w-full text-neutral-500 hover:text-neutral-300 py-2 text-sm font-medium cursor-pointer transition-colors" > Agora não </button> </div> </div> </div> );
}

